### ISSUE TITLE
Corrections dans la création de la table

### ISSUE THREAD

**Issue by B4va** [B4va/iut_bdd#1]
- Vérifier les contraintes `CHECK` : certaines `>=` au lieu de `>` .
- Ajouts de contraintes d'unicité ; cf. ERD.

**Comment by louisfrdh** [comment]
- on a `capacite`, `prix`, `montant`, `qte` en `check` `>0` , je vois pas lesquels devraient être en `>=` ?

- cf ERD tu parles du commit "maj erd" ? je vois rien dessus y a marqué 0 ajout 0 retrait

**Comment by B4va** [comment]
- Pour le `>=` ça ne concerne en fait que prix de la table des plats ; si je me rappelle bien on avait voulu laisser la possibilité de pouvoir créer des "plats" gratuits pour pouvoir préciser certaines options de plats comme ça se fait dans certains restos. ex : Une commande de frites avec également une entrée mayonnaise mais facturée 0€ pour préciser la sauce.
- Pour la contrainte `unique`, et a en croire la représentation graphique initiale de notre bdd, on avait prévu de l'appliquer au champ Genre des types de plat, au champ Libelle des grades et au champ nom_mode des modes de paiements.

**Comment by louisfrdh** [comment]
ok je vois ! 
On s'en occupe cette semaine alors, je fignole mon java là

**Comment by B4va** [comment]
Ai fait les modifs dans les 2 derniers commits :
- [Contraintes d'unicité](https://github.com/B4va/iut_bdd/commit/fc51ca705d669b536067ef9f2d75da6630b7a2a6)
- [Contraintes check](https://github.com/B4va/iut_bdd/commit/0a5ee53ee2db7950f2cfed8acac60b11d04df103)
A tester sur les pc de l'iut...

**Comment by B4va** [comment]
Tests et corrections faites. Idem pour les insertions. :+1:
